version: "3.9"
services:
  fastapi:
    build:
      context: ./apis
      args:
        - MY_UID=${MY_UID}
        - MY_GID=${MY_GID}
        - PORT_FAST=${PORT_FAST}
    volumes:
      - .:/home/appuser/devcon
    env_file:
      - .env
    networks:
      - hackathon_winter_network
    ports:
      - ${PORT_FAST}:${PORT_FAST}
    # expose:
    #   - ${PORT_FAST}
    command: ["/bin/sh", "-c", "/home/appuser/devcon/build.sh"]

  mysql_fast:
    build:
      context: ./mysql
      args:
        - PORT_MYSQL_FAST=${PORT_MYSQL_FAST}
        - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./mysql/data/db:/var/lib/mysql/${MYSQL_DB_FAST}
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    networks:
      - hackathon_winter_network
    ports:
      - ${PORT_MYSQL_FAST}:${PORT_MYSQL_FAST}

  pma_auth:
    build:
      context: ./phpmyadmin
      args:
        PORT_PMA_FAST: ${PORT_PMA_FAST}
    env_file:
      - .env
    networks:
      - hackathon_winter_network
    environment:
      PMA_HOST: ${MYSQL_HOST_FAST}
      PMA_PORT: ${PORT_MYSQL_FAST}
    # expose:
    #   - ${PORT_PMA_FAST}
    ports:
      - ${PORT_PMA_FAST}:${PORT_PMA_FAST}
    volumes:
      - ./phpmyadmin/sessions:/sessions

networks:
  hackathon_winter_network:
    name: hackathon_winter_network
